### PR TITLE
feat: add exclude pattern for links in config

### PR DESCRIPTION
**Pull request by cipherCOM**
See #9 for context. Simple addition to exclude with globs and regex.

### CODE REVIEW

**Comment by cipherCOM** [comment]
@marcelovicentegc my prettier run has many more changes (only trailing commas) in the whole core.ts. So can't help with the prettier_check fail. Or I make the change bigger than it is, by reformatting the core.ts and config.ts, if this is okay with you.

**Comment by marcelovicentegc** [comment]
Hey @cipherCOM! Happy new years! Would you mind just rebasing this PR 🤗? This will make sure that all tests pass 😉

**Comment by cipherCOM** [comment]
@marcelovicentegc rebased and pushed, everything okay now? :)

**Review by marcelovicentegc — APPROVED** [review]
Thanks @cipherCOM! LGTM :partying_face:

**Pull request merged**
