### PR TITLE
feat: create crawler api server

### PR DESCRIPTION
**Pull request by adityak74**
This PR creates an express server that exposes `/crawl` endpoint that accepts the config as a post-request body and responds to the crawled json.

Swagger API Documentation at: `/api-docs`

**_Doesn't support concurrency yet._** - #120 

- [x] Create a basic structure for the server
- [x] Modularize port and host for deployments
- [x] Add validations for config parsing and conversion.
- [x] Swagger UI for API documentation

Fixes: #43

### CODE REVIEW

**Comment by BikeF** [comment]
I did not run your changes, but I am concerned that this API does not support concurrent calls. He cannot be used simultaneously

**Comment by databill86** [comment]
Any news on this feature :)

**Comment by adityak74** [comment]
@databill86 I am working on the docker file, facing some small issues, I should get it in a couple of days.

**Comment by adityak74** [comment]
@databill86 - This PR is ready to be reviewed. I will attempt to Dockerize in another PR. This should get us started with the API running locally.

**Comment by steve8708** [comment]
looks great, thanks for the contribution @adityak74! would be great if you could send a followup PR updating the README about how to use this as an API as well

**Comment by adityak74** [comment]
@steve8708 - Thanks and sure I will create README PR soon.

**Pull request merged**
