### PR TITLE
chore: add prettier check

### LINKED ISSUE #47: Add CI
Would be great to setup github actions to run prettier --check and a build on each PR to ensure those are passing

### PR DESCRIPTION
**Pull request by kunal00000**
This PR is copy of #48 . 
It got messed up while rebasing.

Resolves #47

### CODE REVIEW

**Comment by marcelovicentegc** [comment]
Nice, @kunal00000! It looks like the test workflow is broken, you might need to run `npm run fmt` first (https://github.com/BuilderIO/gpt-crawler/pull/88/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R37)

**Comment by kunal00000** [comment]
Umm 🤔, does this workflow need to have fmt command to fix prettier issues.

**Comment by kunal00000** [comment]
Ah got it 😁

**Review by marcelovicentegc — COMMENTED** [review]
LGTM

**Pull request merged**
